services:
  db:
    image: postgres:17-alpine
    container_name: neiro_calendar
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: neiro_calendar_db
      TZ: Europe/Moscow
      POSTGRES_INITDB_ARGS: "--locale=ru_RU.UTF-8 --lc-collate=C --encoding=UTF-8"
    volumes:
      - ./neiro_pg_data:/var/lib/postgresql/data
      - ./neiro_postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5435:5432"
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d neiro_calendar_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      TZ: Europe/Moscow
    ports:
      - "8085:8080"
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge