spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

  jpa:
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false

  config:
    import: optional:file:.env[.properties]

  output:
    ansi:
      enabled: always

logging:
  config: classpath:logback-spring.xml
